2025-02-01 23:43:02,440 ERROR: Exception on /export_posts [GET] [in C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 730, in _connect
    raise err
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 718, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\owner\Documents\Projects\microblog\app\main\routes.py", line 178, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owner\Documents\Projects\microblog\app\models.py", line 154, in launch_task
    rq_job = current_app.task_queue.enqueue(f'app.task.{name}', self.id, *args, **kwargs)
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\rq\queue.py", line 978, in enqueue
    return self.enqueue_call(
           ~~~~~~~~~~~~~~~~~^
        func=f,
        ^^^^^^^
    ...<15 lines>...
        pipeline=pipeline,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\rq\queue.py", line 721, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\rq\queue.py", line 1103, in enqueue_job
    pipe.execute()
    ~~~~~~~~~~~~^^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\client.py", line 1524, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\owner\Documents\Projects\microblog\venv\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
